name: audit

on:
  
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

  push:
    branches:
      - main
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}